### ISSUE TITLE
Implement Share Experiences: Show Moderation Status

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#172]
## Description
The user must be able to view the review or moderation status on the Share Experiences page.

## Definition of Done
- [x] Pick an arbitrary location and show the `Moderation Review State` as a text label
  - [ ] When a new experience is just *created* or started, the status should initialize/show `Draft`
  - [ ] When the experience has been *shared* or *submitted*, the status should be updated to `In Review` for the corresponding experience in the database. 
    - It is not necessary to display `In Review`, as the user has navigated to the confirmation page.

**Comment by akshathirani** [comment]
@jhlink i would like to work on this issue

**Comment by akshathirani** [comment]
@jhlink, in share experience page after submission,the page redirects to confirm page ,so after submission is it possible to display status as "In Review" on share experience page . as the page has redirected to confirm page or success page

**Comment by jhlink** [comment]
I'm not sure if I'm understanding you, @akshathirani . 

If you're on the confirmation page, you are no longer on the share experience page. Therefore, there is no label or display status to update. That said, I can understand where the confusion might be, and I've clarified the description. 

Let me know if you have additional questions!

**Comment by callummole** [comment]
Implemented in #414.

Slight tweaks from top comment wording. Currently it is implemented as: 
- any newly edited or submitted experience gets updated as `not reviewed`
- the moderation status is shown in `my stories`, and for `moderators`, but the public experiences only shows the moderated stories so doesn't contain the information. 
- currently for the `share_experience` pages the moderation status is _only_ shown to moderators, because they can change it. It is currently not shown to users, because any edited or new submission automatically gets set as `not reviewed`, and they can see the status in `my stories` anyhow.

@gedankenstuecke I am happy to close this since I think it might be confusing to see the moderation status on a story about to submitted.

Perhaps instead we can have a `View` mode, which loads the `share experience` prepopulated, with all info including moderation status, but there is a separate `edit` button. The `View` mode could be reached from a button in `My Stories`

**Comment by gedankenstuecke** [comment]
Thanks @callummole, I think that makes sense. Indeed, the moderation status doesn't need to be listed when writing a new story that's about to be submitted. But I guess there should be some warning of sorts when editing an already published/moderated story, as it'll reset the status?

**Comment by callummole** [comment]
@gedankenstuecke yes, I'll make an issue that adds a View mode and gives a warning.

**Comment by gedankenstuecke** [comment]
great, thanks!

**Comment by callummole** [comment]
Closed in favour of more specific #423
