### ISSUE TITLE
Send a Christmas newsletter

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#363]
### Summary

We should send a newsletter before the Christmas break to update members of the community on progress and invite them to be involved in 2023

### Deadline 

14th Dec 2023 (before @BrainonSilicon goes on leave)

### What needs to be done?
 
- [x] Interview with community member
- [x] Include updates and opportunities 
- [x] Introduce new team 
- [x] Invite to January session
- [x] Draft
- [x] Send
- [x] Upload to GitHub

### Who can help?

* Anything you want included please include in the comments below

**Comment by gedankenstuecke** [comment]
We [made a newsletter draft hackmd](https://hackmd.io/@UvBViadIQhWQzrT5zhenTA/H1YU3pEdi). @GeorgiaHCA will provide general project updates, I will be the person to be interviewed. 

@GeorgiaHCA and I also had marked the 12th of January as the potential date for the community meeting we want to announce. Does that work for you too @BrainonSilicon? Otherwise we can push it back a week!

**Comment by BrainonSilicon** [comment]
I can do the 12th after 12:30. 

From 1-2pm might work the best for me around meetings :)

**Comment by gedankenstuecke** [comment]
Fab, that would fit in well, as we'll also have a visitor that day to give the Coffee Chat talk on his work on Autism and that way we can have him attend the community meeting too!

**Comment by gedankenstuecke** [comment]
@GeorgiaHCA As it's now send: would you be able to put the newsletter on GitHub so that we can close this? :)

**Comment by gedankenstuecke** [comment]
Made a [PR in the old repo](https://github.com/alan-turing-institute/AutisticaCitizenScience/pull/684) where all other newsletters are so far. With that I think we can close this one.
