### ISSUE TITLE
Discussion - Defining titles for contributors

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#408]
### Summary

In the Shared Experiences page there are four placeholder stories. Three are from "Autistic Person" and one is from "Autistic Parent". In PR #401 (where the stories are loaded from a local database) I have hard-coded the Author as "AutSPACEs Contributor". But if this is to be a variable (as the Autistic Person/Autistic Parent choice in the initial layout) suggests - do we want to make the author field part of the PublicExperience Object?

### Deadline 
Ongoing

### What needs to be done?

Discussion could centre around:

* Should there be a field that indicates Author. If so...
* Should the Author be an attribute of the PublicExperience or should it be or should it be the same for all stories
* If the Author is an attribute would users be able to select from a list or self-describe

### Who can help?

* Anyone and Everyone

---

**Comment by gedankenstuecke** [comment]
Thanks for raising this @helendduncan! I would guess that overall we do want some kind of labeling of the author based on self-identification but pinging @GeorgiaHCA as there might have been past discussions or decisions on this. 

Some initial thoughts from me on this: 

* Being able to select a different self-identification for each experience is probably good, as people might want to contribute both their own experiences as well as those of their children in case of people that fit into multiple identifications. 
* Having to pick an identification for each story could be quite annoying for people as it's a repeat task they have to do even if they don't seem themselves in multiple categories. 
  * This becomes even worse if we ask people to just self-describe as then it's not just checking a box but having to fill the text box every time someone wants to add an experience
* Being able to self-identify could be really important, but makes the labeling potentially quite messy 

Based on those considerations I think a **potential solution** could look like this: 

We could ask people to set a *default* identification they want to use. This could be done after account creation when signing in for the first time. This could be the option chosen by default in the form during the experience-entry but could still be changed within that form. Similarly we could offer a range of self-identification options at this stage, while also allowing a custom write-in (similar to how we are currently handling the content warnings for each experience). I think this model might be similar to 'defaults' used in other web platforms that people are familiar with (e.g. default privacy settings for facebook posts). What do other folks think? 🙂 

**Potential technical implementation**: This could be achieved by having a model for self-identification that's in a 1:1 relationship (`OneToOneField`) with the `User` or `OpenHumansMember` model (which I think is [best practice as we don't want to mess with those models](https://docs.djangoproject.com/en/4.1/topics/auth/customizing/#extending-the-existing-user-model)) to store the default identification. This new model could also be expanded in case we want to have people set more defaults or give additional information in the future. In the form we can then pre-populate the identification setting based on this user-setting.

**Comment by GeorgiaHCA** [comment]
We have had lots of discussions around this! As @gedankenstuecke points out, lots of autistic people are also parents and will need the option of talking about their own experience as well as that of others. There are also many other categories of people who may wish to share experiences, such as carers and professionals working with autistic people (e.g. teachers). We thought a box which allows people to self-describe their connection to autism if they want to would be one possibility, although we do want people to say if they identify as autistic. In terms of how the stories are labelled, I think Bastian's suggestion of a default, with the option to switch, is a great one! 

There are some additional complexities - we have a more stringent set of requirements/recommendations for entering experiences on behalf of others than one's own. This is because of autistic people's direct experiences often being elided or distorted, and the desire to uphold an autistic-person first space. One thought we had was to have a reminder of guidance when people enter on behalf of someone else. 

Some experiences will combine multiple perspectives, e.g. a family including autistic parents and children as well as non-autistic children may all take a trip together, and one may wish to report on their varied responses. I think being able to say a post is about multiple experiences would be helpful.

I would suggest we go with the pre-population option @gedankenstuecke suggested for the MVP, with maybe an easy tick box for "includes experiences of another person (or people)" and a clickable link to some guidelines as the next iteration. We can then do lots of user testing to see how well it works for people. 

Would appreciate your thoughts on this too @JamesSCTJ, Susanna, and @BrainonSilicon ?

**Comment by gedankenstuecke** [comment]
I think in that sense it makes sense to handle the _perspective_ of the person reporting similar to the content warnings and let them check one to many pre-defined boxes alongside an open ended _other_ option, e.g. 

_Your perspective for this experience:_

- [x] Autistic person
- [ ] Parent of autistic person
- [x] Caretaker of autistic person
- [ ] Professional working with autistic person
- [ ] Other: _enter freetext_

Based on the settings of the user the different checkboxes could already be pre-ticked. @GeorgiaHCA Do you have a good feeling for which predefined options we should offer? I made those up on the spot now, but you might have a much better idea which ones would be useful and appropriate. These labels don't have to be perfect yet, but would be a good starting point to request further feedback with the MVP with. 🙂

**Comment by gedankenstuecke** [comment]
I think this is now implemented with the author information the share experience form (#554) 🚀
