### ISSUE TITLE
ARIA controls. Use with buttons on dynamically created lists

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#409]
### Summary

In PR #401 stories from a (local) database are shown, users have the option to click "Read Full Story" to expand collapsed stories.
Included in the code to expand the stories are [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) controls which (I believe) could be used to help identify which story is being expanded. I am currently using the title text as the flag as I think that is the most accessible choice but would it be useful upon moderation to have a "short" title specified (and hence expand the PublicExperience class) and use that instead

### Deadline 
Ongoing
### What needs to be done?

Discussion around...
- [x] If aria controls are wanted
- [x] Best way to implement them on pages such as the Shared Stories page

### Who can help?

* 
* 

---

**Comment by gedankenstuecke** [comment]
I'm not super familiar with how *ARIA* works, but the [example that Mozilla gives](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls) for the `aria-controls` part seems to just use the `id` of the `div` rather than an actual textual description for making that linkage. Maybe the solution is to just use the experience ID for the `id` of the expanding panel (as [already implemented here](https://github.com/alan-turing-institute/AutSPACEs/pull/401/files#diff-165158a68d20c7e8b5121f2b89c26bbda084fd0a624910636ad36172c182b302R94))?

**Comment by helendduncan** [comment]
I'm happy to do that - I am not at all familiar with the implementation of ARIA on devices, I will look into it. I will flag that the experience ID is the file UUID so it is a bit unwieldy if it needs to be read to a user

**Comment by gedankenstuecke** [comment]
Thanks! I suspect that the ID is just used for properly linking it internally for accessibility devices and that they aren't being read out/displayed to users, [according to this article](https://tink.uk/using-the-aria-controls-attribute/):

> When a User Agent (UA) supports aria-controls, it makes it possible for focus to be moved from the current element directly to the element it controls.

So it's mostly to automatically redirect the user to the place where a change happened post-press of a button/expand label but not for the "frontend" for the user.

**Comment by callummole** [comment]
@helendduncan. Closed with https://github.com/alan-turing-institute/AutSPACEs/pull/401/commits/d77c82057e6596d61c98119d62663b916e83c540?

**Comment by helendduncan** [comment]
> @helendduncan. Closed with [d77c820](https://github.com/alan-turing-institute/AutSPACEs/commit/d77c82057e6596d61c98119d62663b916e83c540)?

Yes
