### ISSUE TITLE
Moderator feedback to users

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#487]
### Summary
Discussed the possibility of users "spamming" moderators by clicking edit on a rejected story and then saving the form which counts as an edit but has made no change to the story.

Proposed solution/prevention. Allow moderators to provide specific feedback to the users about why a story was rejected. For example "Sentence starting 'The quick brown fox...' contravenes rule 1.23 in the code of conduct" 

Technical implementation: Messaging system needs to be implemented? Add a comment under the story when being viewed or edited?

Moderation implementation: Rules and example responses to be developed

### Deadline 

June 2023

### What needs to be done?

- [ ] Decide on best way to communicate with story writers
- [ ] Decide rules to limit "personal" interactions between story writers and moderators
- [ ] Expand `ExperienceHistory` or make similar for writer-viewable feedback

### Who can help?

* @GeorgiaHCA 
* 

---

### Updates
4th May 2023
#### Some selected relevant comments from 4th May meet up ([link to Google doc](https://docs.google.com/document/d/1mYcTs0kfh8HWK1X87Wc5whARrhH_Rm9xaw2a-uT6UFs/edit#heading=h.caqz9vddyyxh))
* Suggested change is to add a comment to the author - e.g. moderate language in first paragraph
* [with current implementation] It is hard to distinguish which comment is going to author, and which is being made private
* Can we possibly have text boxes asking specifically for the moderator to fill out, including the part of the CoC which is contravened and what part of the experience contravenes it (can be multiple); 
* Might also be nice if there was a link to the COC in the “reply”

**Comment by gedankenstuecke** [comment]
Shall we merge #494 as is and use that as the backbone to improve upon based on today's meeting? 

I feel like the minimal change would just be to change the labels to specifically instruct moderators to use the new textbox to write: 

- which sections of the experience are problematic and, 
- which parts of the CoC are not followed by them (with link to it)?

**Comment by llewelld** [comment]
I guess the question I'd been keen to know the answer to is whether the structure that was discussed during the meeting will ultimately need to be reflected in the database structure. For example, at the moment it's just a single text field for the reply, but maybe it should be a list of CoC references + strings (or CoC refs + "(start, end)" indices into the story)?

If the plan is ultimately to go with this more structured approach, then it would likely need a new table in the database, and merging the current changes might end up causing more mess than benefit.

If we have a clear idea about the end-goal, then I'd personally favour getting the database structure/models corect now, but refining the user interface gradually. If we don't really have that clarity, then I'd go with the changes you suggest @gedankenstuecke. These are just my thoughts on the matter.

**Comment by gedankenstuecke** [comment]
I think that's a very good point @llewelld! I guess it also depends a bit on what we want to use the answers for?

I guess in the current form I would envision those replies being sent through the `oh_member.send_message()` interface to inform people about the reply/moderation being done on their experience. In that case ultimately the responses would end up being purely text again. If we wanted to also be able to do something like statistical analyses or automate responses based etc then a more structured approach would be necessary. 

The main issue I see with the structured approach is that it requires a lot of thinking about potential edge cases. E.g. what happens if one section of an experience breaks multiple sections of our CoC? What if there's multiple sections that break different sections etc? It quickly would become a matter of effectively becoming a "leaving comments on a Google Doc"-type of thing.

I guess by just storing the "final" text in the DB/model we still remain flexible with respect to that if we forgo deeper (automated) analyses of these rejections/comments, as we can tweak the form and form-validation to still have a deeper/complex system if we want, as long as we can concatenate it into a string at the end?

**Comment by KirstieJane** [comment]
Thank you @gedankenstuecke for flagging this issue! And I'm so excited that the project is looking into operationalising these decisions!! So amazing ☀️☀️☀️

Before I went on maternity leave I had always advocated for communications to happen through a different platform. A ticketing system like Jira, or even just email.

The reason being that I don't actually think the edge cases will be that common at the start and I was always focused on getting us going. The implementation of how it would be stored in the database was - in my mind - not part of an MVP.

Has the thinking moved on since then? What would _not_ implementing this change mean?

We WOULD need a process document for how the emails were sent on a consistent basis etc. So this thinking is absolutely valuable, it's just whether comms happen through the app or not is the open question in my mind 💌

**Comment by gedankenstuecke** [comment]
Thanks @KirstieJane! 

One big challenge with the email or Jira approach would be that people need to re-identify themselves outside AutSPACEs to use those, while AutSPACEs has the deidentified communication baked in through the OH API as we can send messages through the API to update the participant on moderation decisions. 

The current MVP implementation that @llewelld already made in #494 offers storing the moderator-responses as free-text in the AutSPACEs backend and could quite easily be expanded for the "send a message through OH". 

But I would agree on maybe not worrying too much about the edge cases. I think merging the existing work with minor front-end tweaks as outlined above might be a good way to have a record of moderation decisions and way for moderators to give feedback!

**Comment by llewelld** [comment]
I've made some changes to PR #494. It's really a prototype to see what you think. The changes make the moderator's reply more structured, but the end result does just end up in the same text field as you suggested @gedankenstuecke (stored as a JSON string). I agree keeping it as a text field in the database allows for more flexibility for the future.

In retrospect I should have gone with your judgement @gedankenstuecke and merged the previous version in first. I'm afraid I was too focused on making these additional changes.

**Comment by gedankenstuecke** [comment]
Wow! First of all let me say that this is a really cool use of JS to make the selection, have the hover with the dropdown appear etc and I'll definitely have a closer look at how you did that in case I ever want to do something similar! 😄 

I fear I have a few concerns about how practical it would be for the moderation approach once we'd move beyond prototype stage: 

1. We would have to encode all content moderation rules into the dropdown approach. The question would then be how granular would we implement those? High-level rules or more granular approaches? 
2. If we go with very granular approaches, how unwieldy will the dropdown become? 
3. If we ever decide to adapt/change the moderation rules we will have to adapt the dropdown items accordingly. I think technically that's definitely doable with the current implementation, but the free-text alternative wouldn't require this. Are we okay with that overhead? 

We can have a chat about it during today's co-working slot and see if we have a consensus between us on the issue. And otherwise we can maybe use the next community meet-up to present a pro/con list of both approaches!

**Comment by llewelld** [comment]
As discussed yesterday, there are now two versions on separate branches:
1. #509
2. #494

**Comment by gedankenstuecke** [comment]
That's amazing, thanks so much @llewelld, I think with that we can easily compare and contrast during the community meet-up and ask for feedback. I think it'll also be good to outline the potential pros & cons of both approaches during that meetup!

**Comment by llewelld** [comment]
Thanks @gedankenstuecke. Excellent idea to outline the pros and cons; I'll prepare and share with you a document on them in advance.

**Comment by gedankenstuecke** [comment]
That would be amazing, thanks so much! Otherwise we also have already a few notes here in the issue

**Comment by llewelld** [comment]
Can this now be closed, or is there more to be done on this task?

**Comment by gedankenstuecke** [comment]
I think this can be closed as #523 is covering the remaining part of this catch all! 👍
