### ISSUE TITLE
Navigation bar formatting

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#489]
### Summary

The spacing of the headers in the navigation bar is uneven. With headers that have drop-downs taking more room than others.

Some justification may be needed when page dimensions are reduced as currently some adjacent headers look like one long section

### What needs to be done?

-[ ] update navigation bar

### Who can help?

* 
* 

---

**Comment by gedankenstuecke** [comment]
Yes, I meant for the experiences and the moderation nav bar items (as on `main` both are now dropdowns). But funnily enough that issue seems to have disappeared now, I noticed it yesterday, but after merging @mastoffel's PR on "My Stories" it is gone! I guess it might have been some JS loading magic and as @mastoffel cleaned that up, that part of the issue is resolved 🎉 

But I'd still be happy to clean up the spacing!

**Comment by helendduncan** [comment]
Sounds good!
