### ISSUE TITLE
Return to previous page from Single Story page

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#540]
### Summary

Following the July 2023 meet up ([Google doc](https://docs.google.com/document/d/1mYcTs0kfh8HWK1X87Wc5whARrhH_Rm9xaw2a-uT6UFs/edit#heading=h.7f28vh3w1oai)): We received feedback that it would be useful if a "back to previous page in same state" button was implemented in the single stories page

### Deadline 
September 2023

### What needs to be done?

- [ ] Implement button
- [ ] Decide on behaviour if story directly linked (go straight to public experiences page?)

### Who can help?

Anyone is welcome to, might clash a bit with work on #531 so mild suggestion of @helendduncan 

---

**Comment by gedankenstuecke** [comment]
I'd say linking back to the public experiences page sounds reasonable to me for the cases where people were opening it from the link. We could also rename the button label to "view all experiences" or something similar in those cases?

**Comment by llewelld** [comment]
Could this be implemented using a `history.back()`? That would hopefully avoid the need to store complex state (django would handle this automatically?) while also ensuring the user's history order is mantained.

https://www.w3schools.com/jsref/met_his_back.asp

**Comment by gedankenstuecke** [comment]
`history.back()` would work for users that come from inside AutSPACEs, but if you are deep-linked to an experience page it would either take you back to wherever else or nowhere in case it's a new window/tab. 

I wonder if we should start using the Django sessions to store all those search/filter parameters: https://docs.djangoproject.com/en/4.2/topics/http/sessions/ 

That way we could restore the states more easily. (Coming to think of it: This would also allow us to avoid having to pass the titles of experiences in URLs as we have for the experience-deletion confirmation!)

**Comment by gedankenstuecke** [comment]
I've implemented the latter (& unrelated) part of this (the passing of the titles in URLs) in #568.

I think the same approach could be taken to store information for the transition between the full _show experiences_ view, the individual experience view and going back. 

For this to work we'd have to store two sets of parameters in the `request.session`, the `trigger_opt_ins` and the `page`, which would allow us to recreate the full request combination of page & labels. 

These session parameters could be set/updated every time a user visits the `show_experiences` page. In case a user is logged in and doesn't have any trigger labels set just yet, we could load them from the `UserProfile` and otherwise start from the blank slate. 

Does that sound reasonable?

**Comment by helendduncan** [comment]
That sounds really sensible
