### ISSUE TITLE
[Improvement] Unify language: experience vs story

### ISSUE THREAD

**Issue by gedankenstuecke** [alan-turing-institute/AutSPACEs#566]
### Summary

Currently the AutSPACEs frontend uses both `Stories` and `Experiences` to describe the data that people enter, and I think it can be confusing for people that aren't familiar with AutSPACEs. I think it would be good to unify it around using either of those terms (but there might also be good reasons to keep both?). 

**Experiences**: 
- Pro: 
  - non-judgemental
  - relatable as "personal experiences"
- Con:
  - could be confused as "experience with" as in skills
  - could be less clear than "story"
  - longer word

**Stories**
- Pro:
  - short
  - quite self-explanatory?
- Con:
  - feels potentially judgemental, c.f. "just-so-stories"

Personally I have to say I'm really not a fan of the term "stories" and try to avoid it when giving presentations or writing/talking about AutSPACEs. I think for me it's because on the one hand calling the contributions "stories" at least runs the risk of devaluing or invalidating people's experiences – and on the other hand it there's a strong tendency among quantitative people to dismiss qualitative data, and calling it "stories" feels to me like we implicitly agree with that. 

But I appreciate that this might be more my own baggage speaking rather than a more general impression. Also there might be an aspect that for contributing users "stories" feels more approachable – so maybe it's a matter of which audience we're talking to? 

What do other folks think?

### What needs to be done?

- [ ] Decide: Do we want to pick one? If so, which one?
- [ ] (Carefully) search & replace the term

### Who can help?

* Anyone with opinions on the matter 😉 
* 

---

**Comment by AlexandraAAJ** [comment]
I would go for experiences with a storytelling aspect that helps identify any learnings behind the experience and inspire other people to share relevant experiences to the community.

**Comment by gedankenstuecke** [comment]
Thanks @giuliatomba and @AlexandraAAJ, I think that mirrors my concerns about "stories" quite a bit. 

I just wonder whether from a "data contributor" perspective, story might feel more inviting, but I guess we might just have to see how people feel about it!

**Comment by Arielle-Bennett** [comment]
I would also agree with the above perspectives on "stories" having connotations around fabrication or perhaps embellishment vs experiences. But as you mention @gedankenstuecke it would be most useful to speak to the data contributors about their views, since "experience" might also result in contributors feeling pressured to include all aspects, including painful details...

**Comment by gedankenstuecke** [comment]
thanks @Arielle-Bennett !

**Comment by aleesteele** [comment]
It's really interesting to read the perspectives above. I would chime in that I perhaps disagree with the notion that "stories" would create more room for dismissal than "experiences". I've seen both used as a means of dismissing qualitative data, with "stories" being dismissed due to their narrative element (seemingly as opposed to more empirical description) and "experiences" being dismissed due to their individualised element (i.e. someone's 'experiences' is their own - and only their own and not more broadly generalisable).

Journalists, anthropologists, and user experience design researchers use the terms "story" and "storytelling" specifically because of this narrative element. This holds power because narrative shapes the way in which people think about an idea, person, concept or event. So I'm guessing that in the context of AutSPACES, the ability to share one's one story, on their own terms and narrative style could shift that power back into that of people, and not just the fields for which storytelling might be their "specialty". Each of these fields has had lots of questions & reflections about power, like this podcast about [anthropology and journalism](https://www.thisanthrolife.org/anthropology-meets-journalism-how-two-fields-can-save-each-other/), or this user experience blog about [narrative bias](https://www.nngroup.com/articles/narrative-biases/). I've found that folks who utilise and think through 'storytelling' may be more attuned to the notion of [situated knowledge](https://www.jstor.org/stable/3178066) and power, i.e. that knowledge production of all kinds, storytelling and otherwise, always come from particular places and particular perspectives, and have implicit power relations tied up in them.

"User experiences" don't necessarily have those kinds of stakes or associations with power that I think user experience researchers in particular have capitalised on, which means that they might be easier to wield and use in this context. I agree with asking the audience and folks who would use this tool what they prefer - and what these two terms mean to them! Thanks for the invitation for feedback, Bastian.

**Comment by gedankenstuecke** [comment]
Thanks for that great counterpoint @aleesteele! It's nice to see the beauty of interdisciplinary work in action as I suspect and see some anecdotal evidence in the comments here for there being some discplinary divides in how people feel about the wording 😄

I guess coming from a biomedical research background "experience" feels something that people are also not super at ease with (when are people ever when it comes to qual. data…) but that has gained some acceptance, maybe also because of the moves towards "personalized medicine" that puts the individual back into medical practice (or at least does so to some level).  

But I definitely hear and have encountered your points about narrative elements and the power that comes with allowing people to "share/tell their story". Which ultimately might mean having to decide on a trade-off between what audience and benefits we want to centre in the project.

**Comment by gedankenstuecke** [comment]
I think based on today's [really great feedback in the community session](https://docs.google.com/document/d/1XGJiSFSNvHV08_oqIUkTvEoHGcU37xgocTxFHdbdq7U/edit) the main take aways are: 

1. Using stories & "sharing a story" seemed to me to be favored a bit due to the power that storytelling has generally,
2. The framing of "stories" can invite people to reflect on their experiences when writing them up – and allows readers to engage with those "personal stories" more to see points of connection
3. There was a sense that one can't "share an experience" in simple text – "having a shared experience" has a different meaning
4. There seemed to be some consensus that we are looking to "write stories about experiences" could be a middle ground solution

I think that framing of "share your sensory processing experiences in a story" is quite good. We can use the "story"-framing in the UI (share story, my stories, read stories, …) – this makes sure that the elements people interact with have a consistent label. In the copy text where there's more space we could use both aspects?

**Comment by gedankenstuecke** [comment]
Copy editing in #621 will include framing _"share your sensory processing experiences in a story"_
