### ISSUE TITLE
Make website compatible with a "reader view" 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#609]
### Summary

It would be useful for users of AutSPACEs to be able to view stories in a reader view to eliminate distractions and make it more comfortable and easier to focus. Currently there is no reader view compatibility. This is important for accessibility as it helps people with sensory overwhelm. 

### What needs to be done?

- [ ] Adapt "view stories" so that they can be put into a reader view and clicked through without having to close the reader view.

**Comment by gedankenstuecke** [comment]
I've started to look into this a bit and it seems that at least some of our pages are already compatible with the reader view as implemented in Safari & Firefox:

For example, on all the "about", "help" etc pages the reader view is being offered. Similarly, the "single story" view offers the reader view as well. Our front page is a bit more tricky, Safari will show the reader view option, but only with very limited details, while Firefox doesn't offer it at all. 

Also, the "view all stories" page does not offer the reader view, probably due to the collapse etc. nature of the page. 

[This SO answer](https://stackoverflow.com/questions/30661650/how-does-firefox-reader-view-operate/40747529#40747529) provides some details on how to improve the reader view rendering (which in turn might also imrpove accessibility by screen readers).

**Comment by gedankenstuecke** [comment]
Okay, I looked into this more and it seems like it won't be as easy to adapt as I had hoped: The collapsing "cards" for each story mean that the content is nested in a way that makes it inaccessible/invisible to the 'readability' libraries that browsers ship with. 

This means we'd have to rewrite this whole page from scratch – to make the default a list of expanded text and then use JS magic to make it hidden (which is basically the opposite of how it works now). 

Given this I'd say for now we put this one into the backburner and instead give the RSS feeds a try, which allows people to subscribe to the content to to have it displayed in the way they prefer in their clients?

**Comment by gedankenstuecke** [comment]
RSS feeds were implemented in #654
